In [1]:
import pandas as pd
import numpy as np

In [2]:
#primero creamos una lista que contenga en si toda las rutas de acceso a los archivos csv
lista=[ f'csv/imeca{2005+i}.csv' for i in range(0,16)]
lista

['csv/imeca2005.csv',
 'csv/imeca2006.csv',
 'csv/imeca2007.csv',
 'csv/imeca2008.csv',
 'csv/imeca2009.csv',
 'csv/imeca2010.csv',
 'csv/imeca2011.csv',
 'csv/imeca2012.csv',
 'csv/imeca2013.csv',
 'csv/imeca2014.csv',
 'csv/imeca2015.csv',
 'csv/imeca2016.csv',
 'csv/imeca2017.csv',
 'csv/imeca2018.csv',
 'csv/imeca2019.csv',
 'csv/imeca2020.csv']

In [3]:
#Realizamos la lectura de todos los archivos csv juntos
DF_list = [(pd.read_csv(f'{i}',sep=',')).replace(-99, np.nan) for i in lista]

In [4]:
#comprobamos que se puedan leer de forma correcta los datos
DF_list[0]

,Fecha,Hora,Noroeste Ozono,Noroeste dioxido de azufre,Noroeste dioxido de nitrogeno,Noroeste monoxido de carbono,Noroeste PM10,Noreste Ozono,Noreste dioxido de azufre,Noreste dioxido de nitrogeno,...,Suroeste Ozono,Suroeste dioxido de azufre,Suroeste dioxido de nitrogeno,Suroeste monoxido de carbono,Suroeste PM10,Sureste Ozono,Sureste dioxido de azufre,Sureste dioxido de nitrogeno,Sureste monoxido de carbono,Sureste PM10
0,01/01/2005,1,19,19,43,42,80,10,22,34,...,26,12,39,27,80,13,15.0,33,29,87.0
1,01/01/2005,2,19,19,42,45,84,7,22,35,...,19,12,34,28,81,9,15.0,31,29,89.0
2,01/01/2005,3,17,19,42,48,88,5,22,34,...,23,12,33,29,84,9,15.0,30,31,90.0
3,01/01/2005,4,16,19,42,52,91,6,22,33,...,21,12,32,29,88,12,15.0,31,33,94.0
4,01/01/2005,5,16,19,39,53,94,8,23,34,...,23,12,31,29,92,19,15.0,29,35,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,31/12/2005,20,15,10,38,18,61,41,12,34,...,33,5,24,9,58,14,2.0,30,15,67.0
8756,31/12/2005,21,12,10,34,20,61,35,12,29,...,27,5,30,11,58,19,2.0,35,17,66.0
8757,31/12/2005,22,9,10,31,23,61,28,12,33,...,19,5,30,12,57,11,2.0,34,19,67.0
8758,31/12/2005,23,8,11,25,27,62,23,12,31,...,22,5,25,14,57,10,3.0,30,21,68.0
8759,31/12/2005,24,9,11,23,30,64,22,12,31,...,20,5,24,15,58,10,3.0,29,22,71.0

In [5]:
DF_list[13]

,Fecha,Hora,Noroeste Ozono,Noroeste dioxido de azufre,Noroeste dioxido de nitrogeno,Noroeste monoxido de carbono,Noroeste PM10,Noreste Ozono,Noreste dioxido de azufre,Noreste dioxido de nitrogeno,...,Suroeste dioxido de nitrogeno,Suroeste monoxido de carbono,Suroeste PM10,Sureste Ozono,Sureste dioxido de azufre,Sureste dioxido de nitrogeno,Sureste monoxido de carbono,Sureste PM10,Unnamed: 27,Unnamed: 28
0,01/01/2018,1,24.0,8,14.0,12.0,106,24.0,5,18.0,...,17.0,8.0,67,5.0,5,25.0,11.0,94.0,NaN,NaN
1,01/01/2018,2,23.0,8,18.0,12.0,107,29.0,5,16.0,...,12.0,7.0,70,8.0,5,21.0,12.0,101.0,NaN,NaN
2,01/01/2018,3,18.0,8,19.0,12.0,108,23.0,5,19.0,...,10.0,7.0,73,4.0,5,21.0,14.0,102.0,NaN,NaN
3,01/01/2018,4,12.0,10,18.0,12.0,110,18.0,5,17.0,...,9.0,7.0,76,6.0,5,18.0,15.0,106.0,NaN,NaN
4,01/01/2018,5,11.0,12,18.0,12.0,113,17.0,5,18.0,...,9.0,6.0,77,4.0,5,20.0,15.0,107.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,31/12/2018,20,20.0,5,26.0,5.0,46,17.0,12,29.0,...,18.0,4.0,26,16.0,5,15.0,3.0,44.0,NaN,NaN
8756,31/12/2018,21,12.0,5,26.0,6.0,49,14.0,12,20.0,...,25.0,5.0,28,11.0,5,19.0,4.0,44.0,NaN,NaN
8757,31/12/2018,22,6.0,5,26.0,7.0,50,11.0,12,21.0,...,26.0,6.0,30,9.0,5,16.0,5.0,45.0,NaN,NaN
8758,31/12/2018,23,4.0,5,22.0,8.0,54,6.0,12,21.0,...,21.0,7.0,31,5.0,5,19.0,6.0,48.0,NaN,NaN
8759,31/12/2018,24,NaN,5,NaN,12.0,61,NaN,12,NaN,...,NaN,12.0,34,NaN,5,NaN,9.0,58.0,NaN,NaN

In [6]:
#el Dataframe número 14 y 15 tienen 32 columnas cuando lo correcto serían 27
#Eliminamos las columnas que sobran
cols = [7,13,19,25,31]
DF_list[14]=DF_list[14].drop(DF_list[14].columns[cols],axis=1)
DF_list[15]=DF_list[15].drop(DF_list[15].columns[cols],axis=1)

In [14]:
indices=( "Fecha"           ,        "Hora"                ,          "Noroeste.Ozono"               ,
 "Noroeste.dioxido.de.azufre"   , "Noroeste.dioxido.de.nitrogeno", "Noroeste.monoxido.de.carbono" ,
 "Noroeste.PM10"                , "Noreste.Ozono"                , "Noreste.dioxido.de.azufre"    ,
 "Noreste.dioxido.de.nitrogeno" , "Noreste.monoxido.de.carbono"  , "Noreste.PM10"                 ,
 "Centro.Ozono"                 , "Centro.dioxido.de.azufre"     , "Centro.dioxido.de.nitrogeno"  ,
 "Centro.monoxido.de.carbono"   , "Centro.PM10"                  , "Suroeste.Ozono"               ,
 "Suroeste.dioxido.de.azufre"   , "Suroeste.dioxido.de.nitrogeno", "Suroeste.monoxido.de.carbono" ,
 "Suroeste.PM10"                , "Sureste.Ozono"                , "Sureste.dioxido.de.azufre"    ,
 "Sureste.dioxido.de.nitrogeno" , "Sureste.monoxido.de.carbono"  , "Sureste.PM10" )

In [8]:
#como se puede observar existe un pequeños inconveniente, por alguna razón el DataFrame crea columnas de más
# las eliminaremos,
#Segundo inconveniente: según la documentación entregada, los valores -99, representan los datos de tipo nan en esta dataset
DF_list[0].isna().sum()

Fecha                             0
Hora                              0
Noroeste Ozono                    0
Noroeste dioxido de azufre        0
Noroeste dioxido de nitrogeno     0
Noroeste monoxido de carbono      0
Noroeste PM10                     0
Noreste Ozono                     0
Noreste dioxido de azufre         0
Noreste dioxido de nitrogeno      0
Noreste monoxido de carbono       0
Noreste PM10                      0
Centro Ozono                      0
Centro dioxido de azufre          0
Centro dioxido de nitrogeno       0
Centro monoxido de carbono        0
Centro PM10                      98
Suroeste Ozono                    0
Suroeste dioxido de azufre        0
Suroeste dioxido de nitrogeno     0
Suroeste monoxido de carbono      0
Suroeste PM10                     0
Sureste Ozono                     0
Sureste dioxido de azufre         3
Sureste dioxido de nitrogeno      0
Sureste monoxido de carbono       0
Sureste PM10                     14
dtype: int64

In [9]:
#ahora eliminamos las columnas que aparecen como sobrantes
DF_list2=[i.dropna(axis=1, how='all') for i in DF_list]
DF_list2[0]

,Fecha,Hora,Noroeste Ozono,Noroeste dioxido de azufre,Noroeste dioxido de nitrogeno,Noroeste monoxido de carbono,Noroeste PM10,Noreste Ozono,Noreste dioxido de azufre,Noreste dioxido de nitrogeno,...,Suroeste Ozono,Suroeste dioxido de azufre,Suroeste dioxido de nitrogeno,Suroeste monoxido de carbono,Suroeste PM10,Sureste Ozono,Sureste dioxido de azufre,Sureste dioxido de nitrogeno,Sureste monoxido de carbono,Sureste PM10
0,01/01/2005,1,19,19,43,42,80,10,22,34,...,26,12,39,27,80,13,15.0,33,29,87.0
1,01/01/2005,2,19,19,42,45,84,7,22,35,...,19,12,34,28,81,9,15.0,31,29,89.0
2,01/01/2005,3,17,19,42,48,88,5,22,34,...,23,12,33,29,84,9,15.0,30,31,90.0
3,01/01/2005,4,16,19,42,52,91,6,22,33,...,21,12,32,29,88,12,15.0,31,33,94.0
4,01/01/2005,5,16,19,39,53,94,8,23,34,...,23,12,31,29,92,19,15.0,29,35,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,31/12/2005,20,15,10,38,18,61,41,12,34,...,33,5,24,9,58,14,2.0,30,15,67.0
8756,31/12/2005,21,12,10,34,20,61,35,12,29,...,27,5,30,11,58,19,2.0,35,17,66.0
8757,31/12/2005,22,9,10,31,23,61,28,12,33,...,19,5,30,12,57,11,2.0,34,19,67.0
8758,31/12/2005,23,8,11,25,27,62,23,12,31,...,22,5,25,14,57,10,3.0,30,21,68.0
8759,31/12/2005,24,9,11,23,30,64,22,12,31,...,20,5,24,15,58,10,3.0,29,22,71.0

In [10]:
 #Revisamos que todos los DataFrame tengan el mismo tamaño
for i in range(0,16):
    print(np.shape(DF_list2[i]))

(8760, 27)
(8760, 27)
(8760, 27)
(8784, 27)
(8760, 27)
(8760, 27)
(8760, 27)
(8784, 27)
(8781, 27)
(8760, 27)
(8760, 27)
(8784, 27)
(8760, 27)
(8760, 27)
(8760, 27)
(8784, 27)

In [16]:
#Renombramos todas las columnas para no generar problemas por los nombres de las mismas
#DF_list2[0].columns
#indices
for i in DF_list2:
    i.columns = indices

In [17]:
#observamos que las columnas sobrantes se fueron
DF_list2[15].isna().sum()

Fecha                              0
Hora                               0
Noroeste.Ozono                   230
Noroeste.dioxido.de.azufre         1
Noroeste.dioxido.de.nitrogeno    230
Noroeste.monoxido.de.carbono     374
Noroeste.PM10                     26
Noreste.Ozono                    229
Noreste.dioxido.de.azufre          0
Noreste.dioxido.de.nitrogeno     229
Noreste.monoxido.de.carbono      373
Noreste.PM10                      43
Centro.Ozono                     231
Centro.dioxido.de.azufre           1
Centro.dioxido.de.nitrogeno      231
Centro.monoxido.de.carbono       375
Centro.PM10                        5
Suroeste.Ozono                   230
Suroeste.dioxido.de.azufre         1
Suroeste.dioxido.de.nitrogeno    230
Suroeste.monoxido.de.carbono     379
Suroeste.PM10                     22
Sureste.Ozono                    231
Sureste.dioxido.de.azufre          1
Sureste.dioxido.de.nitrogeno     231
Sureste.monoxido.de.carbono      375
Sureste.PM10                     321
dtype: int64

In [18]:

DF_all = pd.concat([i for i in DF_list2],axis=0)
DF_all

,Fecha,Hora,Noroeste.Ozono,Noroeste.dioxido.de.azufre,Noroeste.dioxido.de.nitrogeno,Noroeste.monoxido.de.carbono,Noroeste.PM10,Noreste.Ozono,Noreste.dioxido.de.azufre,Noreste.dioxido.de.nitrogeno,...,Suroeste.Ozono,Suroeste.dioxido.de.azufre,Suroeste.dioxido.de.nitrogeno,Suroeste.monoxido.de.carbono,Suroeste.PM10,Sureste.Ozono,Sureste.dioxido.de.azufre,Sureste.dioxido.de.nitrogeno,Sureste.monoxido.de.carbono,Sureste.PM10
0,01/01/2005,1.0,19.0,19.0,43.0,42.0,80.0,10.0,22.0,34.0,...,26.0,12.0,39.0,27.0,80.0,13.0,15.0,33.0,29.0,87.0
1,01/01/2005,2.0,19.0,19.0,42.0,45.0,84.0,7.0,22.0,35.0,...,19.0,12.0,34.0,28.0,81.0,9.0,15.0,31.0,29.0,89.0
2,01/01/2005,3.0,17.0,19.0,42.0,48.0,88.0,5.0,22.0,34.0,...,23.0,12.0,33.0,29.0,84.0,9.0,15.0,30.0,31.0,90.0
3,01/01/2005,4.0,16.0,19.0,42.0,52.0,91.0,6.0,22.0,33.0,...,21.0,12.0,32.0,29.0,88.0,12.0,15.0,31.0,33.0,94.0
4,01/01/2005,5.0,16.0,19.0,39.0,53.0,94.0,8.0,23.0,34.0,...,23.0,12.0,31.0,29.0,92.0,19.0,15.0,29.0,35.0,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,31/12/2020,20.0,25.0,4.0,9.0,2.0,88.0,14.0,4.0,15.0,...,25.0,2.0,14.0,2.0,57.0,21.0,2.0,9.0,3.0,78.0
8780,31/12/2020,21.0,22.0,4.0,9.0,2.0,88.0,11.0,4.0,17.0,...,16.0,2.0,15.0,3.0,57.0,21.0,2.0,9.0,4.0,78.0
8781,31/12/2020,22.0,18.0,4.0,18.0,3.0,88.0,10.0,4.0,17.0,...,9.0,2.0,16.0,3.0,57.0,22.0,2.0,7.0,4.0,78.0
8782,31/12/2020,23.0,16.0,4.0,18.0,5.0,88.0,9.0,4.0,19.0,...,11.0,2.0,15.0,4.0,57.0,29.0,2.0,10.0,4.0,78.0
8783,31/12/2020,24.0,16.0,4.0,18.0,5.0,88.0,11.0,4.0,18.0,...,16.0,2.0,15.0,4.0,60.0,20.0,2.0,12.0,4.0,80.0

In [19]:
DF_all.isna().sum()

Fecha                              21
Hora                               21
Noroeste.Ozono                   1306
Noroeste.dioxido.de.azufre         22
Noroeste.dioxido.de.nitrogeno    1297
Noroeste.monoxido.de.carbono     2027
Noroeste.PM10                     174
Noreste.Ozono                    1299
Noreste.dioxido.de.azufre          21
Noreste.dioxido.de.nitrogeno     1331
Noreste.monoxido.de.carbono      2073
Noreste.PM10                      369
Centro.Ozono                     1319
Centro.dioxido.de.azufre          101
Centro.dioxido.de.nitrogeno      1366
Centro.monoxido.de.carbono       2070
Centro.PM10                       555
Suroeste.Ozono                   1236
Suroeste.dioxido.de.azufre         42
Suroeste.dioxido.de.nitrogeno    1261
Suroeste.monoxido.de.carbono     2050
Suroeste.PM10                     365
Sureste.Ozono                    1319
Sureste.dioxido.de.azufre         126
Sureste.dioxido.de.nitrogeno     1485
Sureste.monoxido.de.carbono      2231
Sureste.PM10                     3201
dtype: int64

In [20]:
#Separación de lainformación por tipo de contenido
#O3 <-    DF_save[0]
#SO2 <- - DF_save[1]
#NO2 <- - DF_save[2]
#CO <- -  DF_save[3]
#PM10 <- -DF_save[4]
DF_save = list()
palabra = ['Ozono','dioxido.de.azufre','dioxido.de.nitrogeno','monoxido.de.carbono','PM10']
for i in range(0,5):
    DF_save.append(DF_all[['Fecha','Hora',f'Noreste.{palabra[i]}',f'Suroeste.{palabra[i]}',f'Noroeste.{palabra[i]}',f'Sureste.{palabra[i]}',f'Centro.{palabra[i]}']])

In [21]:
DF_save[0]

,Fecha,Hora,Noreste.Ozono,Suroeste.Ozono,Noroeste.Ozono,Sureste.Ozono,Centro.Ozono
0,01/01/2005,1.0,10.0,26.0,19.0,13.0,4.0
1,01/01/2005,2.0,7.0,19.0,19.0,9.0,4.0
2,01/01/2005,3.0,5.0,23.0,17.0,9.0,4.0
3,01/01/2005,4.0,6.0,21.0,16.0,12.0,4.0
4,01/01/2005,5.0,8.0,23.0,16.0,19.0,5.0
...,...,...,...,...,...,...,...
8779,31/12/2020,20.0,14.0,25.0,25.0,21.0,18.0
8780,31/12/2020,21.0,11.0,16.0,22.0,21.0,11.0
8781,31/12/2020,22.0,10.0,9.0,18.0,22.0,4.0
8782,31/12/2020,23.0,9.0,11.0,16.0,29.0,6.0
8783,31/12/2020,24.0,11.0,16.0,16.0,20.0,6.0

In [24]:
#Guardamos los datos 

nombres=['O3','SO2','NO2','CO','PM10']
for i in range(0,(len(nombres))):
    DF_save[i].to_csv(f'Datos limpios imeca/{nombres[i]}.csv',index=False)